version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  # app:
  #   image: node:14
  #   working_dir: /api
  #   volumes:
  #     - .:/api
  #   command: bash -c "npm install && npm run start"
  #   ports:
  #     - "3801:3800"
  #   depends_on:
  #     - db